apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-vela-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-vela-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # TODO Nur Rechte vergeben die das Plugin braucht
subjects:
  - kind: ServiceAccount
    name: argocd-vela-sa
    namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vela-sa-secret
  annotations:
    kubernetes.io/service-account.name: argocd-vela-sa
type: kubernetes.io/service-account-token