{{- range .Values.baukasten }}
{{- with . }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  destination:
    namespace: gp-cicd-tools
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ .source.path }}
    repoURL: {{ .source.repoURL }}
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
{{- end }}
{{- end }}