#    run the following commands after uninstalling kyverno helm plugin:
#      kubectl delete validatingwebhookconfiguration kyverno-policy-validating-webhook-cfg;
#      kubectl delete validatingwebhookconfiguration kyverno-resource-validating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-policy-mutating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-resource-mutating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-verify-mutating-webhook-cfg;

kyverno:
  webhooksCleanup:
    enable: true
  cleanupController:
    replicas: 2
    resources:
      requests:
        cpu: 20m
    serviceMonitor:
      enabled: true
  admissionController:
    replicas: 3
    serviceMonitor:
      enabled: true
    container:
      resources:
        limits:
          memory: "1Gi"
  backgroundController:
    replicas: 2
    serviceMonitor:
      enabled: true
    resources:
      limits:
        memory: "256Mi"
  reportsController:
    replicas: 2
    serviceMonitor:
      enabled: true
  policyReportsCleanup:
    enabled: false