#    run the following commands after uninstalling kyverno helm plugin:
#      kubectl delete validatingwebhookconfiguration kyverno-policy-validating-webhook-cfg;
#      kubectl delete validatingwebhookconfiguration kyverno-resource-validating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-policy-mutating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-resource-mutating-webhook-cfg;
#      kubectl delete mutatingwebhookconfiguration kyverno-verify-mutating-webhook-cfg;

kyverno:
  replicaCount: 3
  rbac:
    serviceAccount:
      name: kyverno
  serviceMonitor:
    enabled: true
  webhooksCleanup:
    enable: true
  resources:
    limits:
      memory: 1.5Gi
    requests:
      cpu: 50m
  cleanupController:
    resources:
      requests:
        cpu: 20m

