patch:
  namespace: syn-patch-operator
  serviceAccount: patch-sa
ingress:
  hostname: sso.apps.cluster.example.com
realm:
  internalName: internal

replicas: 1
image: "" # empty => use default image from operator
persistence:
  enabled: true
features:
  # Comma separeted list of features to be disabled
  disabled: "admin2"
  # Comma separeted list of features to be enabled
  enabled: "openshift-integration,token_exchange,impersonation,admin_fine_grained_authz"

provider:
  openshift:
    enabled: true

######################
##    Postgresql    ##
######################
postgresql:
  fullnameOverride: postgresql-keycloak
  service:
    ports:
      postgresql: 5432
  auth:
    username: keycloak # don't override
    database: keycloak # don't override
    existingSecret: keycloak-config # don't override
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    persistence:
      size: 8Gi
  backup:
    enabled: true
    # default values if backu is enabled
    size: 10Gi
    schedule: '0 0 * * *'
    retain:
      days: 8 # need to +1, so 7 days = 8
serviceMonitor:
  name: sso

######################
##      Config      ##
######################
keycloakConfigCli:
  enabled: false

  cluster: dev #c-gepa-play
  host: example.com #gepa.vshnmanaged.net
  
  importer:
    image: 'docker.io/adorsys/keycloak-config-cli:5.5.0-20.0.1'
  
  identityProvider:
    openshift:
      baseUrl: https://api.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}:6443
      clientId: "keycloak"
  
  argoWorkflows:
    enabled: true
    rootUrl: https://workflows.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}
    redirectUris:
      - https://workflows.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}/*
    webOrigins:
      - https://workflows.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}
  
  grafana:
    enabled: true
    rootUrl: https://grafana.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}
    adminUrl: https://grafana.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}
    redirectUris:
      - https://grafana.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}/login/generic_oauth
    webOrigins:
      - https://grafana.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}
  
  sonarqube:
    enabled: true
    redirectUris:
      - "*"
      - https://sonarqube.apps.{{ .Values.keycloakConfigCli.cluster }}.{{ .Values.keycloakConfigCli.host }}/oauth2/callback/saml
  
  vault:
    enabled: true
    rootUrl: https://vault.{{ .Values.keycloakConfigCli.cluster }}.run.gepardec.com
    adminUrl: https://vault.{{ .Values.keycloakConfigCli.cluster }}.run.gepardec.com
    redirectUris:
      - https://vault.{{ .Values.keycloakConfigCli.cluster }}.run.gepardec.com/ui/vault/auth/oidc/oidc/callback
      - https://vault.{{ .Values.keycloakConfigCli.cluster }}.run.gepardec.com//oidc/oidc/callback
      - http://localhost:8250/oidc/callback
    webOrigins:
      - https://vault.{{ .Values.keycloakConfigCli.cluster }}.run.gepardec.com
  
  keycloak:
    fullnameOverride: "gp-sso"