apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ots-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ range $key, $value := .Values.ingress.annotations -}}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name}}
                port:
                  number: 3000
            pathType: ImplementationSpecific
      host: {{ .Values.ingress.hostname }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.hostname }}-tls

