apiVersion: v1
kind: Service
metadata:
  labels:
    app: ots
    {{- include "gp-one-time-secret.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ots
    {{- include "gp-one-time-secret.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
