apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: This SCC builds upon the default OpenShift SCC "nonroot-V2". In Addition to
      this SCC add additional capabilities that allow to change the uid and gid of a container so that images can be built without root access.
  name: nonroot-build
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
  - NET_BIND_SERVICE
  - SETGID
  - SETUID
  - CHOWN
  - FOWNER
  - DAC_OVERRIDE
  - SETFCAP
fsGroup:
  type: RunAsAny
groups: [ ]
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
supplementalGroups:
  type: RunAsAny
users: [ ]
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:nonroot-build
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot-build
    resources:
      - securitycontextconstraints
    verbs:
      - use

