{{- if .Values.GrafanaOperatorDatasources }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ include "gp-multena.name" . }}-proxy-datasource
  namespace: {{ .Release.Namespace }}
spec:
  name: system-datasources.yaml
  datasources:
    - name: thanos-multena
      uid: thanos-multena
      type: prometheus
      url: "http://{{ include "gp-multena.name" . }}:{{ .Values.multena.port }}"
      access: proxy
      editable: true
      isDefault: false
      jsonData:
        httpMethod: POST
        httpHeaderName1: Accept-Encoding
        httpHeaderName2: X-Plugin-Id
        oauthPassThru: true
        manageAlerts: false
      secureJsonData:
        httpHeaderValue1: "*/*"
        httpHeaderValue2: "thanos"
    - name: loki-multena (Application)
      uid: loki-multena-application
      type: loki
      url: "http://{{ include "gp-multena.name" . }}:{{ .Values.multena.port }}/api/logs/v1/application/"
      access: proxy
      editable: true
      isDefault: false
      jsonData:
        httpMethod: POST
        httpHeaderName1: Accept-Encoding
        httpHeaderName2: X-Plugin-Id
        oauthPassThru: true
        manageAlerts: false
      secureJsonData:
        httpHeaderValue1: "*/*"
        httpHeaderValue2: "loki"
{{- end }}