apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: privatebin
    {{- include "gp-privatebin.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: privatebin
      {{- include "gp-privatebin.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: privatebin
        {{- include "gp-privatebin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "privatebin/nginx-fpm-alpine:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name: privatebin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
          - name: configs
            mountPath: /srv/cfg
          - name: data
            mountPath: /srv/data
          - name: run
            mountPath: /run
          - name: tmp
            mountPath: /tmp
          - name: nginx-cache
            mountPath: /var/lib/nginx/tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: configs
          configMap:
            name: {{ .Release.Name }}-configs
            defaultMode: 420
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: { }
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
          {{- else -}}
          emptyDir: { }
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
