{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
          storage: {{ .Values.persistence.size }}
    storageClassName: {{ .Values.persistence.storageClassName }}
{{- end -}}