apiVersion: v1
kind: Service
metadata:
  labels:
    app: privatebin
    {{- include "gp-privatebin.labels" . | nindent 4 }}
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: privatebin
    {{- include "gp-privatebin.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
