apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-secrets
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: keycloak
        property: client-secret-argo-workflows
      secretKey: clientsecretargoworkflows
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: keycloak
        property: client-secret-vault
      secretKey: clientsecretvault
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: keycloak
        property: provider-secret-openshift
      secretKey: providersecretopenshift
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: keycloak
        property: client-secret-grafana
      secretKey: clientsecretgrafana
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: internal-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: client-secrets
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/managed-by: client-secrets
      data:
        secrets.properties: |
          ARGO_WF_CLIENT_SECRET={{ `{{ .clientsecretargoworkflows }}` }}
          VAULT_CLIENT_SECRET={{ `{{ .clientsecretvault }}` }}
          OCP_IP_CLIENT_SECRET={{ `{{ .providersecretopenshift }}` }}
          GRAFANA_CLIENT_SECRET={{ `{{ .clientsecretgrafana }}` }}