{{- if or .Values.persistence.enabled .Values.provider.openshift.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: '{{ .Values.postgresql.auth.existingSecret }}'
  namespace: {{ .Release.Namespace }}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cluster/config/keykloak/
        property: provider-secret-openshift
      secretKey: provider-secret-openshift
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cluster/config/keykloak/
        property: db-password
      secretKey: db-password
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin-internal-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: '{{ .Values.postgresql.auth.existingSecret }}'
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/managed-by: '{{ .Values.postgresql.auth.existingSecret }}'
      data:
        username: {{ .Values.postgresql.auth.username | b64enc }}
        clientSecret: {{`'{{ .provider-secret-openshift }}'`}}
        password: {{`'{{ .db-password }}'`}}
        postgres-password: {{`'{{ .db-password }}'`}}

---
{{- if .Values.provider.openshift.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-keycloak-oauthclient
  namespace: {{ .Values.patch.namespace }}
spec:
  serviceAccountRef:
    name: {{ .Values.patch.serviceAccount }}
  patches:
    patch-oauthclient:
      targetObjectRef:
        apiVersion: oauth.openshift.io/v1
        kind: OAuthClient
        name: keycloak
      patchTemplate: |
        secret: {{`{{ (index . 1).data.clientSecret | b64dec }}`}}
      patchType: application/merge-patch+json
      sourceObjectRefs:
        - apiVersion: v1
          kind: Secret
          name: keycloak-config
          namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}