{{- if .Values.postgresql.backup.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ include "gp-keycloak-instance.fullname" . }}-backup'
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.postgresql.backup.size }}"
  volumeMode: Filesystem
  storageClassName: cephfs-fspool-cluster
{{- end }}