{{- if .Values.keycloakConfigCli.enabled }}
kind: Job
apiVersion: batch/v1
metadata:
  name: kc-config-importer
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    helm.sh/hook: "post-install,post-upgrade,post-rollback"
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "5"
spec:
  backoffLimit: 1
  parallelism: 1
  completions: 1
  template:
    spec:
      volumes:
        - name: config-data
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: secret-data
          secret:
            secretName: client-secrets
      containers:
        - name: keycloak-config-cli
          image: {{ .Values.keycloakConfigCli.importer.image }}
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          terminationMessagePath: /log/termination-log
          env:
            - name: KEYCLOAK_SSLVERIFY
              value: "false"
            - name: IMPORT_FILES
              value: "/config/*"
            - name: KEYCLOAK_CONNECTTIMEOUT
              value: "10s"
            - name: KEYCLOAK_READTIMEOUT
              value: "10s"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "120s"
            - name: IMPORT_VARSUBSTITUTION_ENABLED
              value: "true"
            - name: IMPORT_VALIDATE
              value: "true"
            - name: IMPORT_CACHE_ENABLED
              value: "false"
            - name: KEYCLOAK_URL
              value: "http://{{ include "gp-keycloak-instance.fullname" . }}-service:8080"
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "gp-keycloak-instance.fullname" . }}-initial-admin
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gp-keycloak-instance.fullname" . }}-initial-admin
                  key: password
          volumeMounts:
            - name: config-data
              mountPath: /config
            - name: secret-data
              mountPath: /secrets
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
{{- end }}