{{- if not .Values.customerInstance }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-config-reader
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "gp-keycloak-instance.labels" . | nindent 4 }}
{{- end }}