apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secrets
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    secrets.properties: {{ .Values.clientProperties }}
  template:
    metadata:
      name: client-secrets
      namespace: {{ .Values.namespace }}
