apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-secrets
  namespace: {{ .Release.Namespace }}
spec:
  # Einträge für ARGO_WF_CLIENT_SECRET, VAULT_CLIENT_SECRET, OCP_IP_CLIENT_SECRET, GRAFANA_CLIENT_SECRET
  dataFrom:
    - extract:
        key: keycloak
        conversionStrategy: Default
        decodingStrategy: None
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: admin-internal-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: client-secrets
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/managed-by: client-secrets
      data:
        secrets:
          properties: |
            ARGO_WF_CLIENT_SECRET={{`'{{ .client-secret-argo-workflows}}'`}}
            VAULT_CLIENT_SECRET={{`'{{ .client-secret-vault }}'`}}
            OCP_IP_CLIENT_SECRET={{`'{{ .provider-secret-openshift }}'`}}
            GRAFANA_CLIENT_SECRET={{`'{{ .client-secret-grafana }}'`}}