#https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-the-monitoring-stack
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: {{ .Values.clusterMonitoring.enableUserWorkload }}
    prometheusOperator:
      {{- include "infranodes.enabled" . | nindent 6 }}
    prometheusK8s:
      {{- include "infranodes.enabled" . | nindent 6 }}
      externalLabels:
        cluster_discriminator: {{ .Values.clusterMonitoring.prometheusK8s.clusterName }}
      {{- if .Values.clusterMonitoring.prometheusK8s.remoteWrite.enabled }}
      remoteWrite:
        - url: {{ .Values.clusterMonitoring.prometheusK8s.remoteWrite.url }}
          remoteTimeout: 60s
          queueConfig:
            maxSamplesPerSend: 8000
            maxShards: 30
          basicAuth:
            username:
              name: hub-remote-write-authentication
              key: username
            password:
              name: hub-remote-write-authentication
              key: password
          writeRelabelConfigs:
            - sourceLabels:
                - "__name__"
              regex: "apiserver_request_slo_duration_seconds_bucket|apiserver_request_duration_seconds_bucket|etcd_request_duration_seconds_bucket|apiserver_response_sizes_bucket|rest_client_request_duration_seconds_bucket|rest_client_rate_limiter_duration_seconds_bucket"
              action: "drop"
      {{- end }}
      retention: {{ .Values.clusterMonitoring.prometheusK8s.retention }}
      resources:
        requests:
          cpu: {{ .Values.clusterMonitoring.prometheusK8s.resources.requests.cpu }}
          memory: {{ .Values.clusterMonitoring.prometheusK8s.resources.requests.memory }}
        {{- if .Values.clusterMonitoring.prometheusK8s.resources.limits.cpu }}
        limits:
          cpu: {{ .Values.clusterMonitoring.prometheusK8s.resources.limits.cpu }}
        {{- end }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.clusterMonitoring.prometheusK8s.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.clusterMonitoring.prometheusK8s.storageSize }}
    alertmanagerMain:
      enableUserAlertmanagerConfig: {{ .Values.clusterMonitoring.alertmanagerMain.enableUserAlertmanagerConfig }}
      {{- include "infranodes.enabled" . | nindent 6 }}
      resources:
        requests:
          memory: {{ .Values.clusterMonitoring.alertmanagerMain.resources.requests.memory }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.clusterMonitoring.alertmanagerMain.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.clusterMonitoring.alertmanagerMain.storageSize }}
    kubeStateMetrics:
      {{- include "infranodes.enabled" . | nindent 6 }}
    openshiftStateMetrics:
      {{- include "infranodes.enabled" . | nindent 6 }}
    grafana:
      enabled: false # https://docs.openshift.com/container-platform/4.10/monitoring/accessing-third-party-monitoring-uis-and-apis.html#accessing-third-party-monitoring-uis
      {{- include "infranodes.enabled" . | nindent 6 }}
    telemeterClient:
      {{- include "infranodes.enabled" . | nindent 6 }}
    k8sPrometheusAdapter:
      {{- include "infranodes.enabled" . | nindent 6 }}
    thanosQuerier:
      {{- include "infranodes.enabled" . | nindent 6 }}
