{{- if .Values.backup.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 'gp-vault-backup-pvc'
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.backup.size }}"
  volumeMode: Filesystem
  storageClassName: {{ .Values.backup.storageClass }}
{{- end }}